import { readFileSync, writeFileSync } from "fs"
import { join } from "path"
import { tokens } from "./tokens"
import { tokenKeyToCssVar, sidebarKeyToCssVar } from "./utils"

const GLOBALS_PATH = join(process.cwd(), "app", "globals.css")
const START_MARKER = "    /* GENERATED BY tokens:generate — DO NOT EDIT MANUALLY */"
const END_MARKER = "    /* END GENERATED */"

function generateRootBlock(): string {
  const lines: string[] = [START_MARKER]

  for (const [key, value] of Object.entries(tokens.colors)) {
    lines.push(`    ${tokenKeyToCssVar(key)}: ${value};`)
  }

  lines.push(`    --radius: ${tokens.radius};`)

  for (const [key, value] of Object.entries(tokens.sidebar)) {
    lines.push(`    ${sidebarKeyToCssVar(key)}: ${value};`)
  }

  lines.push(END_MARKER)
  return lines.join("\n")
}

function updateGlobalsCss(css: string, generated: string): string {
  const startIdx = css.indexOf(START_MARKER)
  const endIdx = css.indexOf(END_MARKER)

  if (startIdx === -1 || endIdx === -1) {
    return css
  }

  return css.slice(0, startIdx) + generated + css.slice(endIdx + END_MARKER.length)
}

function main() {
  const isCheck = process.argv.includes("--check")
  const current = readFileSync(GLOBALS_PATH, "utf-8")
  const generated = generateRootBlock()
  const updated = updateGlobalsCss(current, generated)

  if (isCheck) {
    if (current !== updated) {
      console.error("❌ globals.css is out of sync with design-system/tokens.ts")
      console.error("   Run `npm run tokens` to sync.")
      process.exit(1)
    }
    console.log("✅ globals.css is in sync with design-system/tokens.ts")
    return
  }

  if (current !== updated) {
    writeFileSync(GLOBALS_PATH, updated, "utf-8")
    console.log("✅ globals.css updated from design-system/tokens.ts")
  } else {
    console.log("✅ globals.css already in sync")
  }
}

main()
