export const tokens = {
  colors: {
    background: "#f8faf4",
    foreground: "#1c2b18",
    card: "#ffffff",
    cardForeground: "#1c2b18",
    popover: "#ffffff",
    popoverForeground: "#1c2b18",
    primary: "#2f6b3e",
    primaryForeground: "#f8faf4",
    secondary: "#e5eed9",
    secondaryForeground: "#2f6b3e",
    muted: "#d6e4cc",
    mutedForeground: "#547849",
    accent: "#e8a020",
    accentForeground: "#1c2b18",
    destructive: "#c0392b",
    destructiveForeground: "#ffffff",
    border: "#b8d4a8",
    input: "#b8d4a8",
    ring: "#2f6b3e",
    chart1: "#2f6b3e",
    chart2: "#5a9e6f",
    chart3: "#e8a020",
    chart4: "#7fc99e",
    chart5: "#f0c040",
  },
  sidebar: {
    background: "#eef5e6",
    foreground: "#1c2b18",
    primary: "#2f6b3e",
    primaryForeground: "#ffffff",
    accent: "#d6e4cc",
    accentForeground: "#2f6b3e",
    border: "#b8d4a8",
    ring: "#2f6b3e",
  },
  radius: "0.75rem",
  spacing: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    "2xl": "3rem",
    "3xl": "4rem",
  },
  typography: {
    fontSans: "var(--font-geist-sans)",
    fontMono: "var(--font-geist-mono)",
    sizeXs: "0.75rem",
    sizeSm: "0.875rem",
    sizeMd: "1rem",
    sizeLg: "1.125rem",
    sizeXl: "1.25rem",
    size2xl: "1.5rem",
    size3xl: "1.875rem",
    size4xl: "2.25rem",
    size5xl: "3rem",
    weightNormal: "400",
    weightMedium: "500",
    weightSemibold: "600",
    weightBold: "700",
    lineHeightNormal: "1.5",
    lineHeightTight: "1.25",
    lineHeightRelaxed: "1.75",
  },
} as const

export type DesignTokens = typeof tokens
